query AppSettings($version: String) {
  getAppSettings{
    isLive
    merchantId
    merchantKey
    sharedSecretKey
    processor
    region
    orderSuffix
    customNsu
    enableTax
    enableTransactionPosting
    salesChannelExclude
    shippingProductCode
    nexusRegions
  }
}