query AppSettings($version: String) {
  getAppSettings{
    isLive
    merchantId
    merchantKey
    sharedSecretKey
    processor
    region
    orderSuffix
    customNsu
    useOrderIdForFingerprint
    enableTax
    enableTransactionPosting
    salesChannelExclude
    shippingProductCode
    nexusRegions
    merchantDictionary{
      userInput
      isValid
      goodPortion
    }
  }
}